import { writeFile } from 'node:fs/promises';
import jsesc from 'jsesc';
import decodeMapLegacy from '../data/decode-map-legacy.json' with { type: 'json' };
import decodeMapOverrides from '../data/decode-map-overrides.json' with { type: 'json' };
import decodeMap from '../data/decode-map.json' with { type: 'json' };
import encodeMap from '../data/encode-map.json' with { type: 'json' };
import invalidReferenceCodePoints from '../data/invalid-character-reference-code-points.json' with { type: 'json' };
import { regexAsciiWhitelist } from './ascii-whitelist-regex.mjs';
import { regexAstralSymbol } from './astral-symbol-regex.mjs';
import { regexBmpWhitelist } from './bmp-whitelist-regex.mjs';
import { regexEncodeNonAscii } from './encode-non-ascii-regex.mjs';
import { regexInvalidRawCodePoints } from './invalid-code-points-regex.mjs';
import { regexLegacyReferenceSource } from './legacy-reference-regex.mjs';
import { regexNamedReferenceSource } from './named-reference-regex.mjs';

const regexDecimalEscapeSource = '&#([0-9]+)(;?)';
const regexHexadecimalEscapeSource = '&#[xX]([a-fA-F0-9]+)(;?)';
const regexAmbiguousAmpersandSource = '&([0-9a-zA-Z]+)';

const regexDecodeSource = [
	regexNamedReferenceSource,
	regexLegacyReferenceSource,
	regexDecimalEscapeSource,
	regexHexadecimalEscapeSource,
	regexAmbiguousAmpersandSource,
].join('|');

const serialize = (value) => {
	return jsesc(value, {
		compact: true,
		quotes: 'single',
		wrap: true,
	});
};

const exportRegex = (name, source, flags) => {
	// Validate the pattern before emitting it as a literal.
	new RegExp(source, flags);
	return `export const ${name} = /${source}/${flags};\n`;
};

const exportValue = (name, value) => {
	return `export const ${name} = ${serialize(value)};\n`;
};

const toMap = (object, mapKey = (key) => key) => {
	return new Map(
		Object.entries(object).map(([key, value]) => [mapKey(key), value]),
	);
};

const output = [
	'// This file is generated by `scripts/build.mjs`. Do not edit it manually.\n',
	'\n',
	'// All astral symbols.\n',
	exportRegex('regexAstralSymbols', regexAstralSymbol, 'g'),
	'// All ASCII symbols (not just printable ASCII) except those listed in the\n',
	'// first column of the overrides table.\n',
	'// https://html.spec.whatwg.org/multipage/syntax.html#table-charref-overrides\n',
	exportRegex('regexAsciiWhitelist', regexAsciiWhitelist, 'g'),
	'// All BMP symbols that are not ASCII newlines, printable ASCII symbols, or\n',
	'// code points listed in the first column of the overrides table on\n',
	'// https://html.spec.whatwg.org/multipage/syntax.html#table-charref-overrides.\n',
	exportRegex('regexBmpWhitelist', regexBmpWhitelist, 'g'),
	exportRegex('regexEncodeNonAscii', regexEncodeNonAscii, 'g'),
	exportValue('encodeMap', toMap(encodeMap)),
	exportRegex('regexInvalidRawCodePoint', regexInvalidRawCodePoints, ''),
	exportRegex('regexDecode', regexDecodeSource, 'g'),
	exportValue('decodeMap', toMap(decodeMap)),
	exportValue('decodeMapLegacy', toMap(decodeMapLegacy)),
	// Keys are code points (numbers), matching the `parseInt` results they are
	// looked up with.
	exportValue('decodeMapNumeric', toMap(decodeMapOverrides, Number)),
	exportValue(
		'invalidReferenceCodePoints',
		new Set(invalidReferenceCodePoints),
	),
].join('');

await writeFile(new URL('../src/data.mjs', import.meta.url), output);
